name: Cypress Tests

on: push
   
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Use Node.js 16x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install modules
        run: |
          npm install -g pnpm
          pnpm install
      - name: Initialize Server run through tests
        id: cypress-tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
            install: false
            start: npm start
            wait-on: 'http://localhost:3000'
            wait-on-timeout: 300
            config-file: cypress.json
      - name: Create test failure comment
        if: steps.cypress.outcome == 'failure'
        run: gh issue comment --body "Last failed Cypress test run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Create test success comment
        if: steps.cypress.outcome == 'success'
        run: gh issue comment --body "All Cypress tests Passing!!! :)" 
      - name: Fail
        if: steps.cypress.outcome == 'failure'
        run: exit 1