name: Portfolio CI/CD

on:
  pull_request:
    branches: main
jobs:
  cypress-tests:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: src
          fetch-depth: "0"

      - name: Use Node.js 16x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: src/pnpm-lock.yaml

      - name: Install modules
        run: |
          cd src
          npm install -g pnpm
          pnpm install

      - name: Cypress Integration Tests
        id: cypress-integration-tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
            install: false
            start: pnpm run dev
            wait-on: 'http://localhost:3000'
            wait-on-timeout: 300
            config-file: cypress.json
      - name: Cypress Integration Tests Failed
        if: steps.cypress-integration-tests.outcome == 'failure'
        run: gh issue comment --body "Cypress integration tests failed run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Cypress Integration Tests Succeeded
        if: steps.cypress-integration-tests.outcome == 'success'
        run: gh issue comment --body "All Cypress integration tests are passing!!! :)" 
      - name: Fail
        if: steps.cypress-integration-tests.outcome == 'failure'
        run: exit 1

      - name: Cypress e2e Tests
        id: cypress-e2e-tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
            install: false
            start: pnpm run dev
            wait-on: 'http://localhost:3000'
            wait-on-timeout: 300
            config-file: cypress-e2e.json
      - name: Cypress e2e Tests Failed
        if: steps.cypress-e2e-tests.outcome == 'failure'
        run: gh issue comment --body "Cypress e2e tests failed run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Cypress e2e Tests Succeeded
        if: steps.cypress-e2e-tests.outcome == 'success'
        run: gh issue comment --body "All Cypress e2e tests are passing!!! :)" 
      - name: Fail
        if: steps.cypress-e2e-tests.outcome == 'failure'
        run: exit 1
    

