name: CI/CD Flow

on:
  pull_request:
    branches: main
      jobs:
        build-app:
          name: Build App
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
              with:
                path: src
                fetch-depth: "0"
            - name: Use Node.js 16x
              uses: actions/setup-node@v2
              with:
                node-version: "16"
                cache: 'npm'
                cache-dependency-path: src/pnpm-lock.yaml
            - name: Install Modules
              run: |
                cd src
                npm install -g pnpm
                pnpm install

            - name: Create test failure comment
              if: jobs.build-app.outcome == 'failure'
              run: gh issue comment --body "Failed to build app run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 

            - name: Create build success comment
              if: steps.build-app.outcome == 'success'
              run: gh issue comment --body "Build Successful! :)" 

            - name: Fail
              if: steps.build-app.outcome == 'failure'
              run: exit 1

      run-cypress-tests:
        uses: ./.github/workflows/cypress-tests.yaml
