name: Portfolio CI/CD

on:
  pull_request:
    branches: main
jobs:
  cypress-tests:
    name: Cypress Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: src
          fetch-depth: "0"
      - name: Use Node.js 16x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: src/pnpm-lock.yaml
      - name: Install modules
        run: |
          cd src
          npm install -g pnpm
          pnpm install
      - name: Cypress Testing
        id: cypress-testing
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
            install: false
            start: pnpm run dev
            wait-on: 'http://localhost:3000'
            wait-on-timeout: 300
            config-file: cypress.json

      - name: Cypress Tests Failed
        if: steps.cypress-testing.outcome == 'failure'
        run: gh issue comment --body "Cypress tests failed run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Cypress Tests Succeeded
        if: steps.cypress-testing.outcome == 'success'
        run: gh issue comment --body "All Cypress tests are passing!!! :)" 
      - name: Fail
        if: steps.cypress-testing.outcome == 'failure'
        run: exit 1
  run-unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Use Node.js 16x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install modules & Running Unit Tests
        id: unit-testing
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run test

      - name: Unit Tests Failed
        if: steps.unit-testing.outcome == 'failure'
        run: gh issue comment --body "Unit tests failed run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Unit Tests Succeeded
        if: steps.unit-testing.outcome == 'success'
        run: gh issue comment --body "All Unit tests are passing!!! :)" 
      - name: Fail
        if: steps.unit-testing.outcome == 'failure'
        run: exit 1
