name: Unit Tests

on: 
  pull_request:
    branches: main
   
jobs:
  jest-run:
    runs-on: ubuntu-latest
    name: jest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Use Node.js 16x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install modules & Testing
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run test
      - name: Create test failure comment
        if: steps.jest.outcome == 'failure'
        run: gh issue comment --body "Last failed jest test run:https://storage.googleapis.com/cy-test-reporter.appspot.com/${{ github.repository }}/index.html" 
      - name: Create test success comment
        if: steps.jest.outcome == 'success'
        run: gh issue comment --body "All jest tests Passing!!! :)" 
      - name: Fail
        if: steps.jest.outcome == 'failure'
        run: exit 1